
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cat package.json
      - run: npm i @nx/devkit
      - run: cat package.json
      - run: node tools/scripts/publish.mjs stubber-pro-lib --version 0.0.1 --tag beta
      - run: cat package.json
      - run: npm ci
      - run: npm run build
